[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[phases.install]
cmds = ["export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))"]

[phases.build]
cmds = [
  "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) && mvn -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install -Pproduction"
]

[start]
cmd = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.war"
